[package]
name = "crg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
config = "0.13.1"
futures-util = "0.3.21"
hyper = { version = "0.14.18", features = ["client","stream"] }
hyper-rustls = "0.23.0"
serde = { version = "1.0.137", features = ["derive"] }
tracing = "0.1.34"
tracing-bunyan-formatter = "0.3.2"
tracing-futures = "0.2.3"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }

[dev-dependencies]
actix-rt = "2.7.0"
reqwest = { version = "0.11.10", features = ["json"] }
tokio = "1.18.2"
